version: '3.4'

services:
  alpine-siab2-hobo:
    image: REGISTRY_BASE_URL/alpine-siab2:latest
    hostname: 'hobo'
    environment:
      - "domainname=idocker.REALM_DOMAIN_SUFFIX"
      - "HL_USER_USERNAME=hacker"
      - "HL_USER_PASSWORD=compass"
      - "HL_ROOT_PASSWORD=dQ0edEdD6dWZMJj"
    labels:
      - "traefik.port=7681"
      - "traefik.frontend.rule=Host:hobo.REALM_DOMAIN_SUFFIX"
      - "traefik.protocol=http"
    env_file:
      - ./UUID.env
    volumes:
      - ./UUID.gn:/goldnugget/UUID.gn

      
