version: '3.4'

services:
  alpine-siab-hobo:
    image: hackinglab/alpine-siab
    hostname: 'hobo'
    ports:
      - 4200:4200
    environment:
      - "domainname=idocker.REALM_DOMAIN_SUFFIX"
    env_file:
      - ./UUID.env
    volumes:
      - ./UUID.gn:/goldnugget/UUID.gn
